### ISSUE TITLE
Is pushing release version to dev container registry necessary?

### ISSUE THREAD

**Issue by olaals** [equinor/inspection-data-analyzer#87]
**Describe the improvement you would like to see**
Consider removing the push image to dev container registry under .github/workflows/deploy-to-staging.yml. I believe we never pull or use this image.

**How will this change existing functionality?**
I belive this will not change the existing functionality

**How will this improvement affect the current Threat Model?**
No change

Consider removing this:

```yaml
  build-and-push-release-to-dev:
    name: Update containers in dev with version tag
    uses: ./.github/workflows/publish_component.yml
    with:
      Registry: auroradevacr.azurecr.io
      ImageName: robotics/inspection-data-analyzer
      Tag: ${{ github.event.release.tag_name }}
    secrets:
      RegistryUsername: ${{ secrets.ROBOTICS_AURORADEVACR_USERNAME }}
      RegistryPassword: ${{ secrets.ROBOTICS_AURORADEVACR_PASSWORD }}

```
